### ISSUE TITLE
tlg构建

### ISSUE THREAD

**Issue by wwfcnu** [pengzhendong/welm#2]
可以用kenlm基于units.txt和lm.arpa去构建tlg吗

**Comment by pengzhendong** [comment]
你是说用 kenlm 生成 lm.arpa？还是构图 TLG.fst？可以用 kenlm 训练语言模型

**Comment by wwfcnu** [comment]
> 你是说用 kenlm 生成 lm.arpa？还是构图 TLG.fst？可以用 kenlm 训练语言模型

生成lm.arpa部分用kenlm替代srilm，然后基于units.txt和lm.arpa生成lexicon.txt去构建TLG.fst

**Comment by pengzhendong** [comment]
可以
